version: "3.9"
services:
  postgres:
    image: postgres:16.1-alpine3.19
    environment:
      POSTGRES_DB: "test_db"
      POSTGRES_USER: "admin"
      POSTGRES_PASSWORD: "admin"
      PGDATA: "/var/lib/postgresql/data/pgdata"
    restart: always
    volumes:
      - db-data:/var/lib/postgresql/data
      #- ./postgresql.conf:/var/lib/postgresql/data/pgdata/postgresql.conf
    ports:
      - "5432:5432"
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 2G
volumes:
  db-data: