---
# tasks file for first_setup
- name: Upgrate all packages to the latest version
  apt:
    name: "*"
    state: latest

- name: Install common packages
  apt:
    pkg: "{{packages}}"
    state: present

- name: Change Hostname
  hostname:
    name: "{{new_hostname}}"

- name: copy .bashrc & .vimrc for "{{ansible_user}}"
  copy:
    src: "{{item}}"
    dest: "~"
    owner: root
    group: root
    mode: 0644
  with_items:
    - .bashrc
    - .vimrc
