---
# tasks file for roles/install_jenkins
- name: Install Java
  apt: 
    name: openjdk-17-jre
    state: present
    update_cache: yes

- name: Add Jenkins GPG key
  get_url:
    url: https://pkg.jenkins.io/debian-stable/jenkins.io-2023.key
    dest: /etc/apt/keyrings/jenkins-keyring.asc

- name: Add Jenkins apt repository
  apt_repository:
    repo: "deb [signed-by=/etc/apt/keyrings/jenkins-keyring.asc] https://pkg.jenkins.io/debian binary/"
    state: present

- name: Installing Jenkins
  apt: 
    pkg: 
      - jenkins
    state: present
    update_cache: yes