---
# vars file for first_setup
packages:
  - apt-transport-https
  - bash-completion
  - ca-certificates
  - curl
  - dnsutils
  - ncdu
  - net-tools
  - nmon
  - pwgen
  - apache2
  - default-mysql-server

new_hostname: hostNameRole

